Oscbc 15 testing datalink by mock
bacnet-stack/bacnet-stack pull request #253
Opened 2022-04-18 09:17 UTC by Michail-Antropov

Add bacnet/datalink unit test and test datalink/cobs

2022-04-18 17:35 UTC, skarg approved these changes

2022-04-21 15:21 UTC, gregshue requested changes
`test/bacnet/datalink/mock/` must use the standard headers instead of local versions.

2022-04-22 10:41 UTC, Michail-Antropov commented
> @gregshue This headers from a toolchain. The toolchain may not be installed on the test machine and may not be used for unit testing.

2022-04-22 23:29 UTC, gregshue commented on test/bacnet/datalink/mock/CMakeLists.txt
> +	${SRC_DIR}/../ports/rx62n/bacnet.c
No files from `ports/` should be built. They should be mocked instead.

2022-04-25 13:48 UTC, gregshue commented on test/bacnet/datalink/mock/src/arcnet-mock.c
> +bool check_arcnet_receive_src = true;
@Michail-Antropov This global symbol should not exist.  If you must configure behavior of a mock then use a function and a header for the mock, and prepend the function with `<subsystem-prefix>_mock_<noun>_<verb>`.

2022-04-25 13:51 UTC, Michail-Antropov commented on src/bacnet/datalink/datalink.c
> +#include <strings.h>
@gregshue  This header need for using strcasecmp() function. strcasecmp() is place in strings.h, not string.h.
Error is happenes when build for native_posix at least.

2022-04-25 14:33 UTC, gregshue commented on src/bacnet/datalink/datalink.c
> +#include <strings.h>
@Michail-Antropov Thank you.  Please append line with `/* for strcasecmp() */`

2022-04-25 23:33 UTC, gregshue approved these changes

2022-04-26 14:14 UTC, merged