Feature/oscbs 1 win32 port
bacnet-stack/bacnet-stack pull request #423
Opened 2023-04-19 12:52 UTC by cybermag

2023-09-16 13:52 UTC, skarg requested changes

2023-09-16 13:52 UTC, skarg commented on src/bacnet/basic/sys/fifo.h
> +    BACNET_STACK_EXPORT
please remove extra BACNET_STACK_EXPORT

2023-09-16 13:52 UTC, skarg commented on src/bacnet/hostnport.c
> +int host_n_port_context_decode(uint8_t *apdu,
please pass apdu_size and use secure decoding functions.

2024-03-09 00:14 UTC, stargieg commented on src/bacnet/config.h
> +#endif
The Heartbeat should be 60 s.
Tested with Loytec (Cimetrics BACstac runtime v6.4.2.6).
If the Heartbeat is greater than 150s (multiply 2 in bsc_process_srv_awaiting_request() 300s) than
crash the Cimetrics BACstac after 300s. Other People Problem.

But in bsc-socket.h is
```
    /* According 12.56.Y10 SC_Heartbeat_Timeout */
    /* (http://www.bacnet.org/Addenda/Add-135-2020cc.pdf) the recommended default */
    /* value is 300 seconds. */
```
The default is 300s. In this case SC_NETPORT_DISCONNECT_TIMEOUT should be 150s.

2024-10-18 19:24 UTC, closed without merging

2024-10-18 19:24 UTC, skarg commented
Changed branch name to [feature/bacnet-secure-connect-hub](https://github.com/bacnet-stack/bacnet-stack/pull/new/feature/bacnet-secure-connect-hub)